version: '3.3'
services:
  wrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/geocoder-wrapper:${MAPOTEMPO_VERSION:-latest}
    ports:
      - "8081:80" # HOST:CONTAINER, edit only HOST part
    volumes:
        - ./production.rb:/srv/app/config/environments/production.rb
        - ./production.rb:/srv/app/config/environments/development.rb
        - ./poly:/srv/app/poly
    links:
      - redis-cache
      - addok
    environment:
      APP_ENV: production # Swith to "development" for more traces

  addok:
    build: addok
    image: mapotempo/addok:${ADDOK_VERSION:-1.0.0}
    links:
      - redis-server

  redis-cache:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    command: redis-server --save ""

  redis-server:
    image: redis:${REDIS_VERSION:-3.2-alpine}
    volumes:
      - data:/data
    command: redis-server --save ""

volumes:
    data:
