version: '2'
services:
  wrapper:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: mapotempo/geocoder-wrapper:latest
    ports:
      - "8081:80" # HOST:CONTAINER, edit only HOST part
    volumes:
        - ./production.rb:/srv/app/config/environments/production.rb
        - ./production.rb:/srv/app/config/environments/development.rb
        - ./poly:/srv/app/poly
    links:
      - redis-cache
      - addok
    environment:
      APP_ENV: production # Swith to "development" for more traces

  addok:
    build: addok
    image: mapotempo/addok:latest
    links:
      - redis-server

  redis-cache:
    image: redis:alpine
    command: redis-server --save ""

  redis-server:
    image: redis:alpine
    volumes:
      - data:/data
    command: --appendonly yes

volumes:
    data:
